### PR TITLE
Small CSS change and New Video

### PR DESCRIPTION
**Pull request by BenjaminDHorne**
This a pull request for both the css change James requested and the new video on the front page.

Please let me know the css change is to you liking; also I need to fix some stuff on my Ubuntu development environment, so I did not get to fully test the video code I changed. I am going to fix it ASAP and test the video change (I just have to take care of some other work now), but in the mean time if someone wants to look at the changes and see if the new video works, that would be great.

### CODE REVIEW

**Comment by BenjaminDHorne** [comment]
I fixed the link. Does everything else look good? I still need to fix my Linux box for my testing environment.

**Comment by JamesHoustonDavis** [comment]
Sorry, I only just now got my local copy of the website running. The CSS change needs to go in style.less. In particular, you'll want to append:
"
.application{
	max-width:200px;
	float:left;
}
"
and just return base.css to normal. What happens is that anything you put in style.less will get compiled into that weird cached .css we saw before along with everything that's imported. The video looks good. Sorry, I know this is the long way around, but we'll get there.

**Comment by BenjaminDHorne** [comment]
I am pretty sure base.css will catch the .application class as well, but without me testing it, I could be wrong. I will make this change really quick.

**Comment by BenjaminDHorne** [comment]
Okay we should be good. I will make sure my local copy is fixed and I can test it. But I figure these small changes would be easy to just do and get done without.

**Comment by chuck211991** [comment]
Just so information for you two; James is correct, if you put the css change in static/gis/bower_components/jquery-ui/themes/base/base.css, it will be overwritten later. That file belongs to jquery-ui, and you shouldn't modify it (nor should you modify any files under static/gis/bower_components). The correct place to modify css is in static/less/style.less.

Less (http://lesscss.org/) is a more maintainable form of CSS. Check the bin/ folder for some sample steps for installing it (but don't just do them exactly!), as I think you need an older version...

And for the video, I would google "How to embed youtube videos" and use that. We were using Vimeo (I believe).

Don't forget that I'm still email-responsive! If you're having any problems, feel free to ask :).

**Comment by JamesHoustonDavis** [comment]
... more maintainable form of CSS is debatable...

It's not exactly the most common way to embed Youtube videos... but  it shouldn't be hard coded anyways. Let's make the change for now because Mike needs it soon, and then change the way the reference works on the next update.

**Comment by chuck211991** [comment]
I think there is an unterminated comment in that less file...

**Comment by JamesHoustonDavis** [comment]
Fixed..... do as I say not as I do.

**Comment by BenjaminDHorne** [comment]
Got it. That makes sense. Is the embedded youtube not okay? I have used
embedded youtube links on several websites before.

**Comment by JamesHoustonDavis** [comment]
The code functions normally. However,  everything after /iframe is superfluous...

**Comment by BenjaminDHorne** [comment]
Okay, got it. Is this good to go to the dev server?

**Comment by JamesHoustonDavis** [comment]
yes.

**Pull request merged**
