### PR TITLE
Changed the CMS menus to be Horizontal

### PR DESCRIPTION
**Pull request by JamesHoustonDavis**
I changed the menu plugin to give itself a division called CMS_Menu for
styling and create the root next to the first level

I then changed the base show menu command to label itself when it has a
sub menu

Finally I did some styling... I mostly stole from the internet...
because everyone uses the same method.

### CODE REVIEW

**Comment by BenjaminDHorne** [comment]
Awesome! I just noticed this was here. The dev site is up and running with the new step with exception of the static files (so the css will be off), I will transfer those over and we can check it out, and go to the live site.

Then I will check out these changes. Should we include this change in this release I just tagged? or just wait until the next release, which should be in 2 weeks ??? ( still need to discuss with Brian the release schedule).

**Comment by JamesHoustonDavis** [comment]
It would be nice to get this up, but there is no rush, and with your test setup down and Brian and Brenda out of town, that means we don't have anyone to review. So let's just slate it for next release.

I did see that, thank you very much for putting that up. We should let Brian and Brenda know when the static files are up so they can check everything, but so far, it looks good to me. We're still aiming for Friday right?

**Comment by BenjaminDHorne** [comment]
Yep, I am going to finish it up this morning.

**Comment by JamesHoustonDavis** [comment]
Please hold off the website update until Sunday.  These changes will require a cont, t change, and I am detained in England.

**Comment by ibara** [comment]
Detained? I hope it's nothing serious! (I'll make all the jokes after you're back in the US.)
Sure, we'll hold off.

**Comment by BenjaminDHorne** [comment]
No problem. I just merged them as they looked good on my test. But I am
confused why the build failed.

**Comment by JamesHoustonDavis** [comment]
Apparently, everyone is fine with you taking pictures of Stonehenge,  but as soon as you take your dick out.... too bad the UK doesn't have freedom like the US.


Sent from my T-Mobile 4G LTE Device


-------- Original message --------

**Pull request merged**
